error: use actual types for errors when possible
We can't for rust-[miniscript|bitcoin]'s Errors because they don't
implement PartialEq.

This also moves a lot of Result-returning functions into asserting a
sane state.

Signed-off-by: Antoine Poinsot <darosior@protonmail.com>