error: remove unused errors
Now it's done at compile time. Not removing libibtcoinconsensus' one as i expect to get it back

Signed-off-by: Antoine Poinsot <darosior@protonmail.com>